# Generated by Django 5.1.1 on 2024-10-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                (
                    "user_email",
                    models.EmailField(default="johndoe@example.com", max_length=254),
                ),
                ("user_age", models.IntegerField(default=0)),
                ("user_bio", models.TextField()),
                (
                    "user_image",
                    models.ImageField(blank=True, null=True, upload_to="user_profile"),
                ),
            ],
        ),
    ]
