# Generated by Django 5.1.1 on 2024-10-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='ContactMess',
        ),
    ]
