# Generated by Django 5.1.1 on 2024-10-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_recipe_delete_profile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Recipe",
            new_name="UserProfile",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="recipe_description",
            new_name="user_bio",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="recipe_image",
            new_name="user_image",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="recipe_name",
            new_name="user_name",
        ),
    ]
