# Generated by Django 5.1.1 on 2024-10-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_recipe_userprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_email",
            field=models.EmailField(default="johndoe@example.com", max_length=254),
        ),
    ]
