# Generated by Django 5.1.1 on 2024-10-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image",
        ),
        migrations.AddField(
            model_name="image",
            name="original_image",
            field=models.ImageField(
                default="uploads/default.jpg", upload_to="original_images/"
            ),
        ),
    ]
