# Generated by Django 5.1.1 on 2024-10-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_userprofile_user_age_userprofile_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_image",
            field=models.ImageField(blank=True, null=True, upload_to="user_profile"),
        ),
    ]
