# Generated by Django 5.1.1 on 2024-10-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_userprofile_user_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
